### ISSUE TITLE
[FEATURE] 맞춤 추천 기능

### ISSUE THREAD

**Issue by aqswa** [Mt-EB-Rainbow/back#9]
### TODO
- [ ] 추천 알고리즘 테스트 -> 결정
- [ ] 플라스크 서버 세팅, 추천 api 개발
- [ ] 스프링 서버와 연동
